In [4]:
import pandas as pd

In [5]:
# read crime dataset
crime_df = pd.read_csv("D:/DataSets/msc_group_project/Part_1_Crime_Data--_Legacy_Data_(Discontinued_Date_7_22_2023).csv",low_memory=False)

In [7]:
# read addresses dataset
addresses_df = pd.read_csv("D:/DataSets/msc_group_project/addresses_almost_cleaned.csv")

In [22]:
# Extract unique neighborhood names from 'addresses_df'
unique_neighborhoods = addresses_df['neighbourhood'].str.upper().unique()

# Get the unique crime types from the 'Weapon' column in 'crime_df'
unique_crime_types = crime_df['Description'].unique()

unique_weapon_types = crime_df["Weapon"].unique()

# Create a dictionary to store the counts for each crime type in each neighborhood
crime_counts_dict = {'Neighborhood': unique_neighborhoods}

# Iterate through unique crime types
for crime_type in unique_crime_types:
    crime_counts = []
    for neighborhood in unique_neighborhoods:
        # Filter the 'crime_df' DataFrame for the current neighborhood and crime type
        neighborhood_crimes = crime_df[(crime_df['Neighborhood'] == neighborhood) & (crime_df['Description'] == crime_type)]
        crime_counts.append(len(neighborhood_crimes))
    crime_counts_dict[crime_type] = crime_counts
    
# Create a DataFrame from the dictionary
crime_count_df = pd.DataFrame(crime_counts_dict)

In [23]:
crime_count_df

,Neighborhood,COMMON ASSAULT,SHOOTING,LARCENY FROM AUTO,LARCENY,AUTO THEFT,ROBBERY,BURGLARY,ROBBERY - CARJACKING,AGG. ASSAULT,HOMICIDE,ROBBERY - COMMERCIAL,ARSON,RAPE
0,MOUNT WASHINGTON,100,2,381,306,134,27,421,16,44,2,3,2,7
1,FELLS POINT,1237,37,1190,1888,379,581,553,29,594,15,121,5,30
2,CLIFTON,0,0,0,0,0,0,0,0,0,0,0,0,0
3,DOWNTOWN,4341,117,3233,5512,643,2126,1152,58,2020,40,358,28,178
4,ARLINGTON,539,49,173,431,188,213,386,20,378,47,33,16,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,NW COMMUNITY ACTION,0,0,0,0,0,0,0,0,0,0,0,0,0
79,WINCHESTER,223,8,63,129,116,51,121,34,150,7,4,1,7
80,WOODRING,0,0,0,0,0,0,0,0,0,0,0,0,0
81,CURTIS BAY,937,57,345,831,392,214,614,14,611,29,21,19,31
82,MILTON - MONTFORD,0,0,0,0,0,0,0,0,0,0,0,0,0